### ISSUE TITLE
Notation for pointer types is misleading

### ISSUE THREAD

**Issue by 2mac** [davehtaylor/linked_list#1]
You use type declarations such as `Node* head` which are misleading. This is good notation in C++, but in C it is a little bit different.

In C++, I might write

`char* str1, str2;`

This declares 2 variables of type `char*`. However, in C that same line would declare `str1` as a `char *`, and `str2` as a `char` (NOT a pointer).

I'm sure this hasn't created any logical problems in your program yet, but the preferred notation in C would be `Node *head`, because you need one `*` per name.

Also glad to see you committing C code again. <3

**Comment by davehtaylor** [comment]
Hey hey! Nice catch on that. I actually wrote most of this a few semesters ago. The professor had some strange and wildly inconsistent coding style requirements. 

I wanted to commit these, just so they were up here. But I'm actually working on some major refactoring, and will be adding some new features over the next few days, including fixing up the declarations. So definitely check back. I'm always happy to get your perspective on my code :)

And it's definitely been fun writing in C again. The deeper I get, the more I really enjoy it.

**Comment by 2mac** [comment]
You should definitely get on IRC and Mumble more often. I need more C programmers to talk to. :)
